// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dimage,hls_ip_2018_2,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a100tcsg324-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.165000,HLS_SYN_LAT=2,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=26,HLS_SYN_LUT=34,HLS_VERSION=2018_2}" *)

module dimage (
        clk,
        reset,
        counter_dout,
        counter_empty_n,
        counter_read,
        couleur
);


input   clk;
input   reset;
input  [7:0] counter_dout;
input   counter_empty_n;
output   counter_read;
output  [11:0] couleur;

reg[11:0] couleur;

wire    grp_dimage_do_image_fu_58_counter_read;
wire   [11:0] grp_dimage_do_image_fu_58_couleur;
wire    grp_dimage_do_image_fu_58_couleur_ap_vld;

dimage_do_image grp_dimage_do_image_fu_58(
    .ap_clk(clk),
    .ap_rst(reset),
    .counter_dout(counter_dout),
    .counter_empty_n(counter_empty_n),
    .counter_read(grp_dimage_do_image_fu_58_counter_read),
    .couleur(grp_dimage_do_image_fu_58_couleur),
    .couleur_ap_vld(grp_dimage_do_image_fu_58_couleur_ap_vld)
);

always @ (posedge clk) begin
    if ((grp_dimage_do_image_fu_58_couleur_ap_vld == 1'b1)) begin
        couleur <= grp_dimage_do_image_fu_58_couleur;
    end
end

assign counter_read = grp_dimage_do_image_fu_58_counter_read;

endmodule //dimage
