webtalk_init -webtalk_dir /net/e/floupias001/FRACTALE/fractale/Fractale-It/vivado/Mandelbrot/Mandelbrot.sim/sim_1/behav/xsim/xsim.dir/top_Mandelbrot_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 15 13:59:31 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "202409907_1777491908_210660663_640" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b2c565a6-1fe5-438c-9aaa-d622f1b3d891" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e9dd3fc5a9764d6791bc41a453485ec8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.6.1810 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3315.039 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "3 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "143412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3995586749 -regid "202409907_1777491908_210660663_640" -xml /net/e/floupias001/FRACTALE/fractale/Fractale-It/vivado/Mandelbrot/Mandelbrot.sim/sim_1/behav/xsim/xsim.dir/top_Mandelbrot_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /net/e/floupias001/FRACTALE/fractale/Fractale-It/vivado/Mandelbrot/Mandelbrot.sim/sim_1/behav/xsim/xsim.dir/top_Mandelbrot_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /net/e/floupias001/FRACTALE/fractale/Fractale-It/vivado/Mandelbrot/Mandelbrot.sim/sim_1/behav/xsim/xsim.dir/top_Mandelbrot_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
