# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /net/e/floupias001/ok/EN325-Advanced-digital-design/6_HLS/RGB_2_YUV/solution1/impl/ip/main_0/main_0.xci
# IP: The module: 'main_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /net/e/floupias001/ok/EN325-Advanced-digital-design/6_HLS/RGB_2_YUV/solution1/impl/ip/main_0/constraints/main_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /net/e/floupias001/ok/EN325-Advanced-digital-design/6_HLS/RGB_2_YUV/solution1/impl/ip/main_0/main_0.xci
# IP: The module: 'main_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /net/e/floupias001/ok/EN325-Advanced-digital-design/6_HLS/RGB_2_YUV/solution1/impl/ip/main_0/constraints/main_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
