# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.cache/wt [current_project]
set_property parent.project_path C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/decodeur_7seg.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/Affichage_7seg.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/vga_bitmap_640x480.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/Affichage_VGA.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/Gestionnaire_Horloge.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/src/PmodJSTK_Demo.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/ViewController.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/point.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/convergence.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/debounce.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/iteration.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/push_detector.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/src/spiCtrl.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/src/spiMode0.vhd
  C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/sources_1/imports/new/top_Mandelbrot.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/constrs_1/imports/new/NexysA7.xdc
set_property used_in_implementation false [get_files C:/Users/Denis/Desktop/Fractal_NexysA7/Fractal_NexysA7.srcs/constrs_1/imports/new/NexysA7.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top top_Mandelbrot -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_Mandelbrot.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_Mandelbrot_utilization_synth.rpt -pb top_Mandelbrot_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
