#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 15 13:45:06 CET 2020
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim top_Mandelbrot_tb_behav -key {Behavioral:sim_1:Functional:top_Mandelbrot_tb} -tclbatch top_Mandelbrot_tb.tcl -view /net/e/floupias001/FRACTALE/fractale/Fractale-It/vivado/Mandelbrot/top_Mandelbrot_tb_behav.wcfg -log simulate.log
