# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2018.2
# Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/xilinx/vivado/2018.2/Vivado/2018.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7a100tcsg324-1 ../moi_hls_main_2_1.zip
