// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __dimage_do_image_cbkb_H__
#define __dimage_do_image_cbkb_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct dimage_do_image_cbkb_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 12;
  static const unsigned AddressRange = 50;
  static const unsigned AddressWidth = 6;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(dimage_do_image_cbkb_ram) {
        ram[0] = "0b000000000000";
        ram[1] = "0b000000000010";
        ram[2] = "0b000000000100";
        ram[3] = "0b000000000110";
        ram[4] = "0b000000011000";
        ram[5] = "0b000000011001";
        ram[6] = "0b000000101011";
        ram[7] = "0b000000111100";
        ram[8] = "0b000001001100";
        ram[9] = "0b000001011101";
        ram[10] = "0b000001101101";
        ram[11] = "0b000101111110";
        ram[12] = "0b000101111110";
        ram[13] = "0b000110001110";
        ram[14] = "0b001010011110";
        ram[15] = "0b001010101101";
        ram[16] = "0b001110111101";
        ram[17] = "0b001111001101";
        ram[18] = "0b010011001100";
        ram[19] = "0b010011011100";
        ram[20] = "0b010111011011";
        ram[21] = "0b011011101011";
        ram[22] = "0b011011101010";
        ram[23] = "0b011111101001";
        ram[24] = "0b100011101001";
        ram[25] = "0b001110111100";
        ram[26] = "0b100111100111";
        ram[27] = "0b101011100111";
        ram[28] = "0b101111100110";
        ram[29] = "0b101111100101";
        ram[30] = "0b110011010101";
        ram[31] = "0b110111010100";
        ram[32] = "0b110111000100";
        ram[33] = "0b111011000011";
        ram[34] = "0b111010110011";
        ram[35] = "0b111010100010";
        ram[36] = "0b111110010010";
        ram[37] = "0b111110000001";
        ram[38] = "0b111101110001";
        ram[39] = "0b111001100000";
        ram[40] = "0b111001010000";
        ram[41] = "0b110101000000";
        ram[42] = "0b110000110000";
        ram[43] = "0b101100100000";
        ram[44] = "0b101000010000";
        ram[45] = "0b100000010000";
        ram[46] = "0b011100000000";
        ram[47] = "0b010100000000";
        ram[48] = "0b001000000000";
        ram[49] = "0b000000000000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(dimage_do_image_cbkb) {


static const unsigned DataWidth = 12;
static const unsigned AddressRange = 50;
static const unsigned AddressWidth = 6;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


dimage_do_image_cbkb_ram* meminst;


SC_CTOR(dimage_do_image_cbkb) {
meminst = new dimage_do_image_cbkb_ram("dimage_do_image_cbkb_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~dimage_do_image_cbkb() {
    delete meminst;
}


};//endmodule
#endif
