// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _main_HH_
#define _main_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "convergence.h"
#include "dimage.h"
#include "fifo_w8_d1_A.h"

namespace ap_rtl {

struct main : public sc_module {
    // Port declarations 8
    sc_in_clk clk;
    sc_in< sc_logic > reset;
    sc_out< sc_lv<10> > x;
    sc_out< sc_lv<9> > y;
    sc_out< sc_lv<12> > couleur;
    sc_in< sc_lv<32> > zoom;
    sc_in< sc_lv<32> > offset_X;
    sc_in< sc_lv<32> > offset_Y;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    main(sc_module_name name);
    SC_HAS_PROCESS(main);

    ~main();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    convergence* grp_convergence_fu_102;
    dimage* grp_dimage_fu_124;
    fifo_w8_d1_A* sc_fifo_chn_1_fifo_U;
    sc_signal< sc_lv<8> > grp_convergence_fu_102_s_out_din;
    sc_signal< sc_logic > grp_convergence_fu_102_s_out_write;
    sc_signal< sc_lv<10> > grp_convergence_fu_102_out_x;
    sc_signal< sc_lv<9> > grp_convergence_fu_102_out_y;
    sc_signal< sc_logic > grp_dimage_fu_124_counter_read;
    sc_signal< sc_lv<12> > grp_dimage_fu_124_couleur;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<8> > sc_fifo_chn_1_dout;
    sc_signal< sc_logic > sc_fifo_chn_1_empty_n;
    sc_signal< sc_logic > sc_fifo_chn_1_full_n;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_couleur();
    void thread_x();
    void thread_y();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
